### ISSUE TITLE
citac docker images - order of adding citac.tar.gz

### ISSUE THREAD

**Issue by whummer** [citac/citac#2]
Currently, if there is any change in the code base, `build-images.sh` re-builds all `base` and `puppet` images, which makes it a bit difficult to test and try out things quickly.

Are the contents of `citac.tar.gz` an integral part of the `base_*` images? Otherwise, we may consider moving these instructions ...

```
RUN mkdir -p /opt/citac
ADD citac.tar.gz /opt/citac
```

... to the `Dockerfile`s in `environments_puppet`? cc @oliverhanappi

**Comment by oliverhanappi** [comment]
For development purposes you can run citac itself outside of a Docker container. Just install Ruby (>= 1.9.3) and run citac directly on your host. The executed binary and lib files will be automatically mounted to the test containers, so that any change on the host is reflected immediately.

Please note that the commands exposed to the public are located under the `simple` subcommand, hence you need to run `citac simple test` instead of `citac test`. Furthermore you need to move the test directory to `var/specs`.
